#!/bin/sh

set -ev

: ${METRICS_DIR:=/tmp/metrics}
export METRICS_DIR

/bin/env_parse /etc/cetera.conf.j2

HEAP_SIZE=${CETERA_HEAP_SIZE:-512m}
GC_LOG_DIR=${MESOS_SANDBOX:-/tmp}

/usr/bin/java \
  -Dconfig.file=${CETERA_CONFIG} \
  -Xms${HEAP_SIZE} \
  -Xmx${HEAP_SIZE} \
  -Xloggc:${GC_LOG_DIR}/cetera-gc.log \
  -XX:+PrintGCDateStamps \
  -XX:+PrintGCDetails \
  -XX:+PrintGCCause \
  -XX:+PrintTenuringDistribution \
  -XX:+UseGCLogFileRotation \
  -XX:NumberOfGCLogFiles=3 \
  -XX:GCLogFileSize=50M \
  -XX:+ExitOnOutOfMemoryError \
  -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
  -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
  -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
  -Dfile.encoding=UTF-8 \
  -jar ${CETERA_ROOT}/${CETERA_ARTIFACT}

